model_provider = "codex"
model = "gpt-5.2"
model_reasoning_effort = "xhigh"
disable_response_storage = true

[model_providers]
[model_providers.codex]
name = "codex"
base_url = "http://152.53.165.53:3000/v1"
wire_api = "responses"
env_key = "PP_CODEX"

auto_compact_limit = 5000