version: "3.9"

services:
  memgraph:
    image: ${MEMGRAPH_IMAGE:-memgraph/memgraph:latest}
    ports:
      - "7687:7687"
    volumes:
      - memgraph_data:/var/lib/memgraph

volumes:
  memgraph_data:
